#### NumPy (Numerical Python) is a Python library used to do fast mathematical and scientific calculations.

In [4]:
%pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [87]:
import numpy as np 

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr)

[1 2 3 4 5 6 7 8 9]


In [88]:
print(arr[::-1])

[9 8 7 6 5 4 3 2 1]


In [89]:
## create a 1-D array 

import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [90]:
# 1-D array

arr2 = np.array([1, 2, 3 ,4, 5, 6])
arr2.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [91]:
# 2-D array

arr3 = np.array([[1, 2, 3, 4],[6, 7, 8, 9]])
print(type(arr3))
print(arr3.shape)

<class 'numpy.ndarray'>
(2, 4)


In [92]:
np.arange(1, 10 , 2)

array([1, 3, 5, 7, 9])

In [93]:
np.arange(1, 10 , 2).reshape(5, 1)

array([[1],
       [3],
       [5],
       [7],
       [9]])

In [94]:
np.ones((4, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [95]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [96]:
import numpy as np
arr5 = np.array([[1, 2, 3, 4, 5],[5, 6, 7, 8, 9]])
print(f"Array :-\n {arr5}")
print()
print(f"Array size is: {arr5.size}" )
print(f"Array dimentions is: {arr5.ndim}")
print(f"Array type is: {arr5.dtype}")
print(f"item size (in byte) is: {arr.itemsize}")

Array :-
 [[1 2 3 4 5]
 [5 6 7 8 9]]

Array size is: 10
Array dimentions is: 2
Array type is: int64
item size (in byte) is: 8


In [97]:
# attribute wise operations in array

arr6 = np.array([1, 2, 3, 4, 5])
arr7 = np.array([12, 23, 34 ,45, 56])

print(f"Addition of array : {arr6+arr7}")
print(f"Substraction of array is : {arr6-arr7}")
print(f"multiplication of array is : {arr6*arr7}")
print(f"division of array is : {arr6/arr7}")

Addition of array : [13 25 37 49 61]
Substraction of array is : [-11 -21 -31 -41 -51]
multiplication of array is : [ 12  46 102 180 280]
division of array is : [0.08333333 0.08695652 0.08823529 0.08888889 0.08928571]


In [98]:
# universal operations in array


arr8 = np.array([1, 2, 3, 4, 5, 6])
print(np.sqrt(arr8))

print(np.exp(arr8))

print(np.sin(arr8))

print(np.cos(arr8))

print(np.tan(arr8))

print(np.log(arr8))


[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501 -0.29100619]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [99]:
arr9 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])


In [100]:
arr9

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [101]:
print(arr9[0][3])

4


In [102]:
print(arr9[0:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [103]:
print(arr9[1:, 2:])

[[ 7  8]
 [11 12]]


In [104]:
print(arr9[0:2,1:])

[[2 3 4]
 [6 7 8]]


In [105]:
print(arr9[1: , 1:3])

[[ 6  7]
 [10 11]]


In [107]:
## modify the array 


arr9[0, 0] = 100
print(arr9)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [109]:
## Stastical concept -- Normalization 
## to have mean of 0 and std deviation of 1 

data = np.array([1, 2, 3, 4, 5])

mean = np.mean(data)
print(f"mean is {mean}")

std_dev = np.std(data)
print(f"standard deviation is :- {std_dev}")

normalization = (data-mean) / std_dev
print(f"normalization data :-{normalization}")

mean is 3.0
standard deviation is :- 1.4142135623730951
normalization data :-[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [111]:
## Stastical concept -- Normalization 
## to have mean of 0 and std deviation of 1 

data = np.array([1, 2, 3, 4, 5])

mean = np.mean(data)
print(f"mean is {mean}")

std_dev = np.std(data)
print(f"standard deviation is :- {std_dev}")

median = np.median(data)
print(f"median is :- {std_dev}")

variance = np.var(data)
print(f"variance is {variance}")



mean is 3.0
standard deviation is :- 1.4142135623730951
median is :- 1.4142135623730951
variance is 2.0


In [112]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

data>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [113]:
data[data>5]

array([ 6,  7,  8,  9, 10])

In [114]:
data[(data>=5)&(data<=8)]

array([5, 6, 7, 8])